# frozen_string_literal: true

source "https://rubygems.org"
gemspec

gem 'wdm', '>= 0.1.0' if Gem.win_platform?

group :jekyll_plugins do
  gem 'jekyll-sitemap'
  gem 'jekyll-seo-tag'
  gem 'jekyll-remote-theme'
  gem 'jekyll-timeago'
end
