source "https://rubygems.org"

gem "jekyll", '~> 4.2', :git => 'https://github.com/jekyll/jekyll.git'
gem 'wdm', '>= 0.1.0' if Gem.win_platform?

group :jekyll_plugins do
  gem 'jekyll-sitemap'
  gem 'jekyll-seo-tag'
  gem 'jekyll-remote-theme'
  gem 'jekyll-timeago'
end

